server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:todo-list-api-database
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Crée les tables automatiquement
    show-sql: true  # Affiche les requêtes SQL générées dans la console
  h2:
    console:
      enabled: true
      path: /h2-console  # Accéder à la console H2
