name: "deploy to dev"

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]

env:
  DOCKER_IMAGE: bricekm/todo-list-api-dev
  IMAGE_TARBALL_FILENAME: todo-list-api-dev-docker-image.tar
  DOCKER_USER: bricekm
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
  UPLOAD_NAME: docker-artifact
  UPLOAD_PATH: artifacts

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev

    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.UPLOAD_NAME }}
          path: ${{ env.UPLOAD_PATH }}
      - run: docker load < $UPLOAD_PATH/$IMAGE_TARBALL_FILENAME
      - name: Deploying image to public Docker Hub
        run: .github/workflows/docker_push.sh
